sudo: required
dist: precise
language: php
php:
- 7.4
- 8.0
- 8.1
matrix:
  fast_finish: true
before_script:
- composer self-update
- composer install --dev
- composer require satooshi/php-coveralls:* --dev
script:
- mkdir build
- mkdir build/coverage
- vendor/bin/phpunit
